packages:
  - apps/*
  - packages/*
  - packages/hijraah-*
  - browser-r2-worker

catalog:
  '@ai-sdk-tools/artifacts': 0.4.0
  '@ai-sdk-tools/devtools': 0.6.1
  '@ai-sdk-tools/store': 0.1.2
  '@ai-sdk/anthropic': ^2.0.8
  '@ai-sdk/deepseek': ^1.0.10
  '@ai-sdk/fireworks': ^1.0.10
  '@ai-sdk/gateway': ^1.0.15
  '@ai-sdk/google': ^2.0.11
  '@ai-sdk/mistral': ^2.0.12
  '@ai-sdk/openai': ^2.0.22
  '@ai-sdk/react': ^2.0.45
  '@supabase/supabase-js': ^2.57.4
  '@trigger.dev/sdk': ^4.0.2
  '@types/node': ^22.8.6
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  '@types/uuid': ^10.0.0
  '@typescript-eslint/eslint-plugin': ^8.43.0
  '@typescript-eslint/parser': ^8.43.0
  '@upstash/redis': ^1.35.3
  '@upstash/vector': ^1.2.2
  '@vitest/coverage-v8': ^1.0.0
  ai: 5.0.45
  ai-sdk-devtools: ^0.5.1
  cheerio: ^1.0.0-rc.12
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.5
  eslint: ^9.35.0
  firecrawl: ^4.3.4
  langchain: ^0.3.29
  next: 15.5.2
  nextjs: ^0.0.3
  node-cache: ^5.1.2
  openai: ^5.16.0
  postgres: ^3.4.7
  react: ^19.0.0
  react-dom: ^19.0.0
  stream-browserify: ^3.0.0
  tailwind-scrollbar: ^4.0.2
  tsup: ^8.0.0
  turndown: ^7.2.0
  typescript: ^5.8.3
  util: ^0.12.5
  uuid: ^11.1.0
  vitest: ^1.0.0
  zod: ^4.1.4

catalogMode: strict
