packages:
  - "apps/*"
  - "packages/*"
  # Shared packages following Turborepo best practices
  - "packages/hijraah-*"

  # Keep only browser-r2-worker temporarily for testing
  - "browser-r2-worker" # Legacy worker to be migrated
