name: CI

on:
  push:
    branches: [master, main, develop, release/*]
  pull_request:
    branches: [master, main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Added to support diffing for type location checks

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Type Definition Locations
        if: github.event_name == 'pull_request' # Only run on PRs
        run: |
          # Get the base of the PR
          BASE_REF="master" # Using master as the base branch based on workflow config
          echo "Base ref for PR: $BASE_REF"

          # Get list of new or modified .ts/.tsx files in this PR
          git fetch origin $BASE_REF
          MERGE_BASE=$(git merge-base HEAD "origin/$BASE_REF")

          # Files added (A) or modified (M)
          CHANGED_FILES=$(git diff --name-status --diff-filter=AM $MERGE_BASE HEAD -- 'src/**/*.ts' 'src/**/*.tsx' | awk '{print $2}')

          if [ -z "$CHANGED_FILES" ]; then
            echo "No .ts or .tsx files were added or modified."
            exit 0
          fi

          echo "Checking files for global type definitions outside src/types/:"
          echo "$CHANGED_FILES"

          VIOLATIONS=""

          for FILE_PATH in $CHANGED_FILES; do
            echo "Checking: $FILE_PATH"

            # Rule 1: Allow files in src/types/
            if [[ "$FILE_PATH" == src/types/* ]]; then
              echo "  SKIPPED: File is in src/types/"
              continue
            fi

            # Rule 2: Allow component-local type files (common patterns)
            if [[ "$FILE_PATH" == src/components/**/types.ts ]] || \
               [[ "$FILE_PATH" == src/app/**/types.ts ]] || \
               [[ "$FILE_PATH" == src/features/**/types.ts ]] || \
               [[ "$FILE_PATH" == src/_core/**/types.ts ]] || \
               [[ "$FILE_PATH" == src/_shared/**/types.ts ]] || \
               [[ "$FILE_PATH" == src/pages/**/types.ts ]] || \
               [[ "$FILE_PATH" == src/lib/**/types.ts ]] || \
               [[ "$FILE_PATH" == src/hooks/**/types.ts ]] || \
               [[ "$FILE_PATH" == supabase/functions/_shared/types.ts ]]; then
              echo "  SKIPPED: File matches allowed pattern for local types."
              continue
            fi
            
            # Rule 3: Check for global type definitions
            if grep -q -E -H -n --color=never '^(export|declare)\s+(type|interface|enum)\s+' "$FILE_PATH"; then
              echo "  VIOLATION: Global type found in $FILE_PATH"
              VIOLATIONS="${VIOLATIONS}\n  - ${FILE_PATH} contains global type definitions and is outside 'src/types/' or allowed component paths."
            else
              echo "  OK: No global types found (or file is allowed)."
            fi
          done

          if [ -n "$VIOLATIONS" ]; then
            echo -e "::error::Found type definition violations:${VIOLATIONS}"
            echo -e "Please move global type definitions to src/types/ or appropriate domain subdirectory."
            exit 1
          else
            echo "All checked files adhere to type location guidelines."
          fi

      - name: Security Audit
        run: pnpm run security:audit-ci
        continue-on-error: false

      - name: Type check
        run: pnpm run type-check

      - name: Lint
        run: pnpm run lint

      - name: Format check
        run: pnpm run format:check

      - name: Build
        run: pnpm run build
        env:
          NEXT_PUBLIC_SITE_URL: http://localhost:3000
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

      - name: Test
        run: pnpm test --passWithNoTests

      - name: Upload security audit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-audit-report
          path: |
            security-audit-report.json
            security-audit-summary.md
          retention-days: 30
